from __future__ import annotations

from typing import Protocol

from domain.models.order_intent import OrderIntent


class BrokerPort(Protocol):
    async def get_account(self) -> dict: ...
    async def get_positions(self) -> list[dict]: ...
    async def get_quote(self, symbol: str) -> dict: ...
    async def submit_order(self, order_intent: OrderIntent) -> dict: ...
    async def cancel_order(self, broker_order_id: str) -> dict: ...
    async def get_order_status(self, broker_order_id: str) -> dict: ...
